name: Deployment Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-deep: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --no-audit --no-found --no-optional
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run Build
      - name: Tests
        run: npm test


      

